definitions:
  models.AliasListResponse:
    properties:
      aliases:
        items:
          $ref: '#/definitions/models.AliasResponse'
        type: array
    type: object
  models.AliasResponse:
    properties:
      alias:
        type: string
      email:
        type: string
    type: object
  models.EmailListResponse:
    properties:
      emails:
        items:
          type: string
        type: array
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.StatusResponse:
    properties:
      running:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: christian@scheid.tech
    name: Christian Scheid
    url: https://github.com/scheidti/docker-mailserver-aliases
  description: API for managing aliases in a Docker Mailserver container
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Docker Mailserver Aliases API
  version: "1.0"
paths:
  /v1/aliases:
    get:
      consumes:
      - application/json
      description: Gets a list of all available email aliases from the Docker Mailserver
        container
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AliasListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: List of all available email aliases
      tags:
      - Aliases
  /v1/emails:
    get:
      consumes:
      - application/json
      description: Gets a list of all available email addresses from the Docker Mailserver
        container
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.EmailListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: List of all available email addresses
      tags:
      - E-Mails
  /v1/status:
    get:
      consumes:
      - application/json
      description: Checks if the Docker Mailserver Docker container is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StatusResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Checks Mailserver Docker container
      tags:
      - Utility
swagger: "2.0"
