name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@latest

    - name: Test
      run: |
        mkdir -p ./frontend/dist
        touch ./frontend/dist/index.html
        gotestsum --format pkgname --junitfile TestResults-${{ matrix.go-version }}.xml

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "TestResults-${{ matrix.go-version }}.xml"
      if: always()
